### ISSUE TITLE
Error on modifMat table

### ISSUE THREAD

**Issue by fernanda-ordonez** [Maxime5G/EvoScope#3]
Hello,
Hope you're doing well. I'm trying to run evoscope but after running pastml at the "Reconstructing the mutations from the ACR" part I get the following error:
Error in [.data.frame(modifMat, , c("node", eventOrder)) :
undefined columns selected
Calls: [ -> [.data.frame
<img width="816" alt="Captura de Pantalla 2023-08-21 a la(s) 10 40 41" src="https://github.com/Maxime5G/EvoScope/assets/66924998/1e245e84-c109-4f32-a2ab-4854372a2bac">

I checked the AnnotateATree_WithMasks_Clean.R script and I think the error might be in this line:
if (length(allIDsInTheTree) != nrow(modifMat)){stop('Error reading ACR file - please make sure the format is correct! Exiting...')}
As it's expecting information from the tips and nodes of the tree, but modifMat only include information about the tips (?) 

After I tried to run it with the test data to see if my inputs were the problem, but using the test data I get the following error: 

<img width="988" alt="Captura de Pantalla 2023-08-21 a la(s) 10 43 53" src="https://github.com/Maxime5G/EvoScope/assets/66924998/89e79eaa-6fc2-4ee1-a9d5-7d0f8500cccb">
<img width="889" alt="Captura de Pantalla 2023-08-21 a la(s) 10 45 32" src="https://github.com/Maxime5G/EvoScope/assets/66924998/35a56edc-6f23-4941-9c8a-364b7a20a298">

Thank you for your time, and I would really appreciate if you could help me solve this problem. 

Best, 
Fernanda

**Comment by Maxime5G** [comment]
Hi!

First: which version of pastml and pandas did you use? With the new pandas version, there might be some issues.

Second: you might have some informations in the stderr files. In them, you can find the line where the script failed. If you don't find this informative, I could have a look at your intermediate files and try to fix eventual issues in the code.

**Comment by Maxime5G** [comment]
In the absence of feedback, I'm closing this issue. Feel free to open a new one if you encounter similar issues
