### ISSUE TITLE
Please fix the bug with eventIDs in AnnotateATree_WithMasks_Clean.R

### ISSUE THREAD

**Issue by garushyants** [Maxime5G/EvoScope#4]
Hi!
I was trying to use your pipeline (v 1.0.2), but ran into problem with AnnotateATree_WithMasks_Clean.R 
I installed all the versions of packages as suggested in your manual.
I have R 4.1.2 and on the line 26 of the script read.table causes crash. If replace read.table with read.csv it works. Can you please fix it?

Best regards,
Sofya Garushyants

**Comment by Maxime5G** [comment]
Hello!
Could you please elaborate a little bit on the issue? Like what's the command line you sued, what your input file looks like etc. That'll help me identifying the issue and fix appropriately the script :)

Best,

Maxime.

**Comment by garushyants** [comment]
I started evoscope with default parameters and it broke with the following command (as specified in *_commandsUsed.tab:
Command: Rscript /home/garushyantss2/distr/EvoScope-1.0.2/Scripts/AnnotateATree_WithMasks_Clean.R test_ecoli20230109/test_ecoli20230109_ACRFOLDER/named.tree_tree_evoscope_rescaled_nwk.nwk test_ecoli20230109/test_ecoli20230109_ACR.tab test_ecoli20230109/test_ecoli20230109_ACR_tree.nwk test_ecoli20230109/test_ecoli20230109_ACR_clean.mat test_ecoli20230109/test_ecoli20230109_eventIDs.in

With the error (as in *_stderr.err ):
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 3 did not have 2 elements
Calls: read.table -> scan
Execution halted

When I started looking into problem with AnnotateATree_WithMasks_Clean.R, it turns out that the problem occurs in line 25:
eventOrderFile <- read.table(args[5])

read.table (at least in R 4.1.2) requires more parameters, and that is why this line is causing the issue. If you replace read.table with read.csv the script finishes without errors.

**Comment by Maxime5G** [comment]
Thanks again for noticing this issue! I've fixed it in the latest commit.
