### ISSUE TITLE
Running test data

### ISSUE THREAD

**Issue by annecmg** [Maxime5G/EvoScope#6]
Hi, 
I installed evoscope and I wanted to test the installation using the test data.
I have run `./evoscope -t TestData/ThreeWCPairs_forTests.tab -T TestData/align_cured_UbyT_2_tree_rooted`
However the run does not finish and I attach the error file: [out_stderr.err.gz](https://github.com/user-attachments/files/15982878/out_stderr.err.gz)
The requirements are installed via conda and I also attach the yml file: [evoscope.yml.gz](https://github.com/user-attachments/files/15982883/evoscope.yml.gz)
Any ideas what is going wrong and how to fix this? Thanks a lot!
Anne

**Comment by Maxime5G** [comment]
Hi Anne,

I believe the issues are related to incompatibilities between pastml and newer version of pandas, numpy and scipy. 
I prepared a requirements file which should contain the correct dependencies: [reqs_correct.txt](https://github.com/user-attachments/files/15985362/reqs_correct.txt). These dependencies were built on a linux machine.

For the pastml installation, I would also recommend downgrading to pastml 1.9.40. So the installation steps should be as follows:

```
conda create -n evoscope --file reqs_correct.txt
conda activate evoscope
pip install pastml==1.9.40
```

Could you try and let me know if that would work for you?

**Comment by annecmg** [comment]
Thanks, this works!

**Comment by Maxime5G** [comment]
Awesome - I'll close this issue and I'll actually add the requirements file + install instructions to the repo.
