### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by bnc45581** [Maxime5G/EvoScope#7]
Hi. I am working on installing EvoScope for a project. I have used the conda installation instructions, but am unable to run the 'make' execution to create epocs, epics, and epocs_mcmc.
This is what I did:
Installed R v 4.0.0, installed packages "tidyverse", "gplots", and "ape"
Copied over requirements.txt to my directory
conda create -n evoscope --file requirements.txt
conda activate evoscope
pip install pastml==1.9.40
Tried various commands with make. "make", "evoscope make", "evo-scope make", and "./evoscope make"

Any help would be greatly appreciated! Thanks!

**Comment by Maxime5G** [comment]
Hello!

Just to be 100% sure before digging: have you cloned the repo locally? After setting up your conda environment, clone the repository and then you'll be able to install the tools. This should work:
```
git clone https://github.com/Maxime5G/EvoScope
cd EvoScope
make
```

Let me know if that is of any help :)

Best,

Maxime.

**Comment by bnc45581** [comment]
Hello!
Thank you for the quick response. I don't know why I didn't think of this. It now works.
Thanks so much,
Bran

**Comment by Maxime5G** [comment]
Great! I took the opportunity to update the README :)
I'm closing the issue now that it is resolved. 
Best,
Maxime.
